version: "3.8"
services:

  redis:
      image: redis
      container_name: redis

  django_app:
    build: .
    volumes:
      - .:/weather_app
    ports:
      - 8000:8000 
    image: django_app:weather_app
    container_name: django_weather_app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db 

  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/weather_app/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
    
  celery:
    restart: always
    build:
      context: .
    command: 
      - /bin/bash
      - -c
      - |
        celery -A weather_track.celery worker -l info 
    volumes:
      - .:/weather_app
    container_name: celery
    depends_on:
      - db
      - redis
      - django_app

  celery_beat:
    restart: always
    build:
      context: .
    command: 
      - /bin/bash
      - -c
      - |
        celery -A weather_track beat -l info
    volumes:
      - .:/weather_app
    container_name: celery_beat
    depends_on:
      - db
      - redis
      - django_app
