# Generated by Django 4.0.6 on 2022-09-03 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DecimalField(decimal_places=0, max_digits=2)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dailymeasurement')),
            ],
        ),
    ]
