# Generated by Django 4.0.6 on 2022-09-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_stationsmeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationsmeasurement',
            name='Humidity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='stationsmeasurement',
            name='Overcast',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='stationsmeasurement',
            name='Wind',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
