# Generated by Django 4.0.6 on 2022-09-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_stationsmeasurement_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationsmeasurement',
            name='Humidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stationsmeasurement',
            name='Overcast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stationsmeasurement',
            name='Wind',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
